### ISSUE TITLE
Refactor Governance example to use the new foundry template

### ISSUE THREAD

**Issue by capossele** [risc0/risc0-ethereum#1]
- [ ] Should move the Governance example from `risc0/` repo to `risc0/ethereum`
- [ ] Should close #7 alongside this one.
- [ ] Update doc links to the new repository `risc0-ethereum`

**Comment by capossele** [comment]
With https://github.com/risc0/risc0/pull/1525 we want to drop all ethereum related crates from risc0. We should move the current version of the governance or un updated one on this repo, and adjust the links on the risc0 website to point on this repo

Unfortunately we don't have effective link checkers to help manage 404 errors, but these places come to mind as likely to have links to the ethereum demos.

the [use cases page](https://dev.risczero.com/api/next/use-cases)
the [examples page](https://dev.risczero.com/api/next/zkvm/examples)
blogs -- [on governance](https://www.risczero.com/blog/governance) and [on coprocessors](https://www.risczero.com/blog/a-guide-to-zk-coprocessors-for-scalability) (sherry or vee can support on getting links in these fixed)

**Comment by Cardosaum** [comment]
Blocked on issues with `remappings.txt`
