### ISSUE TITLE
[BUG] RLP error when running erc20-counter example

### ISSUE THREAD

**Issue by EmanHerawy** [risc0/risc0-ethereum#137]
## Bug Report

Hi guys
The code  for this example `risc0-ethereum/examples/erc20-counter` is reverting in this [line](https://github.com/risc0/risc0-ethereum/blob/881e3447f44779debb5ca5852da6c48fd908c0cd/examples/erc20-counter/apps/src/bin/publisher.rs#L101). I couldn't figure out why but I tried to run it via `test-local-deployment.sh` and manually step by step and it always reverts in this line. 

## Steps to Reproduce

1. run `test-local-deployment.sh` 

## Your Environment

- risc0-ethereum version: `cargo-risczero 0.21.0`
- Rust version:
```bassh
 cargo --version --verbose
cargo 1.76.0 (c84b36747 2024-01-18)
release: 1.76.0
commit-hash: c84b367471a2db61d2c2c6aab605b14130b8a31b
commit-date: 2024-01-18
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.1 vendored)
libcurl: 8.5.0-DEV (sys:0.4.70+curl-8.5.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.04 (jammy) [64-bit]

```
- Platform/OS: WSL

## Additional context
```bash
     Running `target/debug/publisher --chain-id=31337 '--rpc-url=http://localhost:8545' --contract=0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0 --token=0x5FbDB2315678afecb367f032d93F642f64180aa3 --account=0x9737100D2F42a196DE56ED0d1f6fF598a250E7E4`
For block 4 calling `balanceOf(address)` on 0x5FbDB2315678afecb367f032d93F642f64180aa3 returns: 100
proving...
Error: invalid account proof

Caused by:
    0: RLP error
    1: RlpIncorrectListLen

```

**Comment by nategraf** [comment]
You might want to check your version of Foundry and Anvil. A previous version of Anvil had a bug that effected it's account proof generation. You can update to the latest version with `foundryup`.

**Comment by nategraf** [comment]
Ah, ok. So this indicates the version of RISC Zero you having installed does not match the one used by the example. To fix this, you should checkout out the `release-1.0` branch of this repo[^1], and install the 1.0 version of RISC Zero, either by using `cargo binstall` or using the new `rzup` install script[^2].

[^1]: https://github.com/risc0/risc0-ethereum/tree/release-1.0
[^2]: https://github.com/risc0/risc0?tab=readme-ov-file#getting-started

**Comment by EmanHerawy** [comment]
It seems we have another error related to buffer size " not sure " 

`proving...
Error: failed to fill whole buffer
Cleaning up...
Killing Anvil (PID 2150)...
Verifying state...
Error: 
error sending request for url (http://localhost:8545/)
`

**Comment by EmanHerawy** [comment]
FYI: I haven't changed anything in the example

**Comment by nategraf** [comment]
> It seems we have another error related to buffer size " not sure "
> 
> `proving... Error: failed to fill whole buffer Cleaning up... Killing Anvil (PID 2150)... Verifying state... Error: error sending request for url (http://localhost:8545/) `

Can you provide any more info here. I don't really have any particular ideas based on this.

I do know I've seen that error related to version mismatches. Make sure that all the `Cargo.toml` files in your project (including the root and in the guest directory) reference the same version of the zkVM (making sure all dependencies with `risc0-` at the start are on "1.0"), and that is the version installed (`cargo risczero --version`). Hopefully it's as simple as that, but if not I definitely want to find the root cause.

**Comment by nategraf** [comment]
We also opened https://github.com/risc0/risc0/issues/2003 to discuss and improve the error message here.

**Comment by EmanHerawy** [comment]
> > It seems we have another error related to buffer size " not sure "
> > `proving... Error: failed to fill whole buffer Cleaning up... Killing Anvil (PID 2150)... Verifying state... Error: error sending request for url (http://localhost:8545/) `
> 
> Can you provide any more info here. I don't really have any particular ideas based on this.
> 
> I do know I've seen that error related to version mismatches. Make sure that all the `Cargo.toml` files in your project (including the root and in the guest directory) reference the same version of the zkVM (making sure all dependencies with `risc0-` at the start are on "1.0"), and that is the version installed (`cargo risczero --version`). Hopefully it's as simple as that, but if not I definitely want to find the root cause.
> 
> I took a quick look through the code on the `release-1.0` branch, and it all seems to be using the right dependency versions: https://github.com/risc0/risc0-ethereum/tree/release-1.0

TBh, I did nothing  rather than, cloning the example and running it and this is the error I got, no further details. unfortunately I can't reproduce it cuz I had new fresh ubunto installed now " I had to remove the old env, apologize"  

now in ubuntu 2024 machine I have the version issue again but it's crazy cuz I can't find this version at all  . below is the error  with `RUST_BACKTRACE=1`. 

`proving...
Error: failed to fill whole bufferthread 'main' panicked at risc0/r0vm/src/lib.rs:192:18:
called `Result::unwrap()` on an `Err` value: incompatible client version: 1.1.0-alpha.1, server version: 1.0.0

Stack backtrace:
   0: anyhow::kind::Adhoc::new
   1: risc0_zkvm::host::api::server::Server::run
   2: risc0_r0vm::main
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: main
   5: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
   6: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
   7: _start
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: risc0_r0vm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`
I think the issue with version mismatch arises when anyhow tries to handle the error , not sure though i'm still beginner in rust

**Comment by nategraf** [comment]
Ah, this error is more helpful. It indicates that your `risc0-zkvm` dependency is set to `1.1.0-alpha.1` (the development version on main in https://github.com/risc0/risc0), which does not match the version of `cargo risczero` you have installed. You can also run `cargo tree -i -p risc0-zkvm` to see which version of `risc0-zkvm` is currently in use, and where it is being imported from.

I just tried this on the `release-1.0` branch and did not get this error. Are you on the `release-1.0` branch? `main` is the development branch and is not stable.

**Comment by EmanHerawy** [comment]
OMG, finally, it works. Yes,  I was on 'main' ; I was cloning and using it without checking out to any other branch . Thank you for your help and your time

**Comment by nategraf** [comment]
Thanks for working through that, and sorry that the errors are so hard to debug. We are working on improving that now!
