### ISSUE TITLE
Bonsai integration CI job fails due to jq not being installed

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-ethereum#143]
Some of the self-hosted Linux machines have jq installed and some do not. We need to either ensure jq is installed, or not use it in the test script we use in the Bonsai integration test on `risc0-ethereum`

**Comment by morgangibbs87** [comment]
This should be solved now. `jq` was installed and confirmed on the remaining self-hosted runners.

This PR is awaiting approval, but its contents have already been applied:
https://github.com/risc0/devops/pull/231
