### ISSUE TITLE
[BUG] groth16::encode takes a owned Vec<u8> when it could take a slice

### ISSUE THREAD

**Issue by mothran** [risc0/risc0-ethereum#174]
## Bug Report

https://github.com/risc0/risc0-ethereum/blob/main/contracts/src/groth16.rs#L25

In the groth16::encode() method it would be nice if the seal param was a slice instead of a Vec so I could avoid a clone pulling the seal from a receipt.

**Comment by nategraf** [comment]
Closed by https://github.com/risc0/risc0-ethereum/pull/179
