### ISSUE TITLE
Upgrade toolchain to rustc 1.81

### ISSUE THREAD

**Issue by Wollac** [risc0/risc0-ethereum#291]
Several crates of the alloy family (like `op-alloy`) currently require or will soon require rust 1.81.

**Comment by mahmudsudo** [comment]
can i take on this issue?

**Comment by nategraf** [comment]
> can i take on this issue?

This is blocked on release of the 1.81 Rust toolchain for guests. @SchmErik is working on this, and we'll be able to solve this issue once that is done. With that, there won't be a lot to do. So this particular issue does not need help.
