### ISSUE TITLE
Fix documentation on the `CONTROL_ID` constants in the `RiscZeroGroth16Verifier.sol`

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-ethereum#30]
Comment highlighted below is inaccurate:
https://github.com/risc0/risc0-ethereum/blob/37e4cb9805f9180364a66cdef919d7c32e6fe8c8/contracts/src/groth16/RiscZeroGroth16Verifier.sol#L89-L95

**Comment by pdg744** [comment]
Also not clear to me what `control id` is being referenced here: https://github.com/risc0/risc0-ethereum/blob/main/contracts/src/groth16/ControlID.sol

**Comment by nategraf** [comment]
Addressing this in a pair of PRs. https://github.com/risc0/risc0-ethereum/pull/80 to `risc0-ethereum` is the first, and I'll open one to `risc0` with the associated bootstrap changes.
