### ISSUE TITLE
Mark the Steel history feature with `unstable`

### ISSUE THREAD

**Issue by Wollac** [risc0/risc0-ethereum#310]
We can use the `stability` crate that we use in `risc0` and mark the `history` module with `#[unstable(feature = "history")]`. With this, we can get this out in the next release and start to get feedback without committing to the exact API or endorsing it for production just yet.

**Comment by nategraf** [comment]
We'll want to do this before putting history into a release that's marked `1.x`. Marking the `risc0_steel::history` module with `[unstable(feature = "history")]` should do the trick. That'll break anything that depends on it, so it'll certainly break the `commitment_block` method, which we'll want to mark with the same macro.
